version: "3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

## Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/prometheus.yaml


## Grafana
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    container_name: grafana
    depends_on:
      - prometheus
    env_file:
      - ./grafana/config.monitoring