global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: 'website'
#   scheme: https
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification
    static_configs:
      - targets: ['hassan.oulcaid.com:9100']

  - job_name: 'Desktop'
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification
    static_configs:
#      - targets: ['X.X.X.X:9100']      # Add an endpoint to monitor

  - job_name: 'Loki'
    tls_config:
      insecure_skip_verify: true  # Skip SSL verification
    static_configs:
        - targets: ['loki:3100']